### ISSUE TITLE
ESP32 example missing

### ISSUE THREAD

**Issue by rschoell** [syssi/esphome-dps#31]
Hi Syssi, 

I would like to use your implementation on an ESP32 variant. You're mentioning this in your README.MD file as well, but it seems not to be there. Can you please advise?

Many thanks
Ralph

**Comment by syssi** [comment]
I will prepare and push an example this weekend. May be you would like to contribute the YAML. Just remove the `esp8266` section from the current example and add

```
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
```

instead. That's all.
